### ISSUE TITLE
Any way te get to recovery if a full erase was done?

### ISSUE THREAD

**Issue by Mutini** [Ryogo-Z/nook_ntx_6sl_twrp#1]
OK, so I did something stupid on mt Nook Glow Plus. I installed TWRP and did a full erase of everything. Basically thinking this device was like a phone.

I have TWRP latest installed, and just wanted to know if recovery can accessed? When I power on the device, it starts, then turns off within about 3 seconds, not a good sign.

**Comment by Ryogo-X** [comment]
I see only two options:
1) consequently interrupt boot 5 times;
2) disassembly device and connect to serial console;

**Comment by Ryogo-X** [comment]
If you erased bootloader partition then I fear I don't know how to help you. If bootloader partition is intact then serial console could help you.

**Comment by juppin** [comment]
The bootloader isn´t located on any partition.
It´s located between the partition table and the first partition.
You can erase the bl only if you overwrite the first mega byte of your sd card / emmc device.
And therefore at least fastboot should work if you wipe all partitions in twrp.

**Comment by Ryogo-X** [comment]
**juppin** yes, you are correct.
Therefore I think serial console should help to unbrick device, since you can get to fastboot from there.

**Comment by Mutini** [comment]
Thanks for the response. I guess if there's any hope for recovery it's through a serial console, otherwise I'll just sell it for parts. I bought it cheap second hand, so not a big loss.

Any tutorials showing how to accomplish a serial console connection? I'm assuming the unit needs to be cracked opened and some points soldered to a serial connector.

This unit does not stay powered on, would that affect connecting via a serial console?

**Comment by Ryogo-X** [comment]
**Mutini** you need to look a thread at [XDA](https://forum.xda-developers.com/nook-touch/general/nook-glowlight-plus-t3230323/page3) for details about serial console.

>This unit does not stay powered on, would that affect connecting via a serial console?

Not sure.

**Comment by Mutini** [comment]
I was SOOOOOO close!!!

So here's the deal. I checked out that thread you linked, and read some comments from those trying to understand a nook code dump. They pointed out that there's a possible touch sequence in the code to activate various recovery modes.

~~So I decided to give it try. On my third try, I got into recovery mode. The touch sequence I think I used was...~~

~~1. Power on unit with finger always on the Home (Nook) button~~
~~2. As soon as screen lights up, let go of power button, keep finger on Home button, and place a finger between the edge of screen and the "n" in nook, and place another finger between edge of screen and the "k" nook. If it doesn't work at first, try placing your fingers closer to the n & k. Or try above the n & k.~~

~~That apparently got me back into recovery, and TWRP was still the recovery.~~

Above info is wrong, button sequence is not implemented. Apparently if you're in a boot loop, booting the nook 5 times should get you into recovery.

I then screwed up again. I decided to try and install a update.zip file through TWRP. At first I got a wrong version error. So I opened the update.zip file with winrar and edited the updater script to the version it was asking for. It then flashed the update.zip, but now I'm in a total recovery boot loop, and TWRP was erased as the recovery, and the stock recovery is now installed. 

I'm not sure, but I might of edited the build.prop too.

What exactly is the proper way to flash the system back to the Nook when it's been completely erased?

So now I'm pretty much screwed, since there's no way to ADB in, and there does not appear to be a button sequence that activates fastboot.

I ordered a uART Serial converter, and plan to try to Putty my way into activating Fastboot. It looks really simple to do, so I'll update on what happens. Hopefully it will work while in a recovery boot loop.

**Comment by Ryogo-X** [comment]
>That apparently got me back into recovery, and TWRP was still the recovery.

Actually, what got you into recovery was 5 consequent interrupted boots :)
The dual fingers method does not work due to BN screwed up this part of source code and never really cared to fix it.

>What exactly is the proper way to flash the system back to the Nook when it's been completely erased?

Just flashing update.zip from TWRP should be sufficient.

**Comment by Mutini** [comment]
I see. What's confusing me, is my nook isn't exactly booting since it's in a loop. I guess each loop counts as an interrupted boot.

**Comment by Ryogo-X** [comment]
>I guess each loop counts as an interrupted boot.

should be so.

**Comment by Mutini** [comment]
Damn, if they implemented that button sequence this would have been a non-issue. Hopefully the the uART serial console can get me to flash back TWRP.

You said flashing update.zip works in TWRP, but I was getting a version check error when trying to flash update.zip. Is that normal?

**Comment by Ryogo-X** [comment]
>You said flashing update.zip works in TWRP, but I was getting a version check error when trying to flash update.zip. Is that normal?

you still need to patch that check in updater-script, but nothing more

**Comment by Mutini** [comment]
> you still need to patch that check in updater-script, but nothing more

When you say "patch that check" you're referring to changing the model name in the updater-script from "ntx_6sl" to "nook_ntx_6sl" ?

getprop("ro.product.device") == "nook_ntx_6sl" || abort("This package is for \"ntx_6sl\" devices; this is a \"" + getprop("ro.product.device") + "\".");

**Comment by Ryogo-X** [comment]
>you're referring to changing the model name in the updater-script from "ntx_6sl" to "nook_ntx_6sl" ?

yes
