### ISSUE TITLE
ro.product.device isn't universal

### ISSUE THREAD

**Issue by ScottESanDiego** [Ryogo-Z/nook_ntx_6sl_twrp#2]
The ro.product.device property is set for a Glowlight 3 (aka nook_ntx_6sl), so flashing factory updates from BN on a Glowlight Plus fail due to the mismatch.

(Easy enough to fix, just annoying)

**Comment by Ryogo-X** [comment]
Uploaded new release (3.3.1), ro.product.device now changed to "ntx_6sl".
