### ISSUE TITLE
Glowlight 7.8" Doesn't Load Recovery

### ISSUE THREAD

**Issue by hcors** [Ryogo-Z/nook_ntx_6sl_twrp#3]
Hi, 

I am unable to boot into TWRP, when loading it seems to flash the screen white and then goes black and sits there. Another 7.8" Nook user on the XDA forums reports shes having the same issue of it not loading. 

https://forum.xda-developers.com/nook-touch/general/glowlight-plus-7-8-2019-t3934677/post81210917#post81210917

**Comment by hcors** [comment]
!! I just confirmed with a second device on current firmware, the TWRP does not load. Loads a black screen only. !!

**Comment by akachyantim** [comment]
> 
> 
> !! I just confirmed with a second device on current firmware, the TWRP does not load. Loads a black screen only. !!

Hello author,
Just wonder any chance(or plan) to fix this issue on 7.8? ^^;

**Comment by Ryogo-X** [comment]
@akachyantim sure thing! Just need to get some free time somehow.

**Comment by akachyantim** [comment]
> 
> 
> @akachyantim sure thing! Just need to get some free time somehow.

Oh great!. I was about to return my 7.8. I can wait.... I can't wait!  Thank You!

**Comment by Ryogo-X** [comment]
@hcors @akachyantim I'm afraid I have no clues what the issue is, so I may need your help.
Here's a test build:
[test_build_v1.zip](https://github.com/Ryogo-Z/nook_ntx_6sl_twrp/files/4222708/test_build_v1.zip)
even if it would boot into black screen - could you please confirm if adb works?

**Comment by hcors** [comment]
It boots up further than before. Loads the screen to say "Unmodified System Partition", but when I try to slide the slider or press anything it doesn't do anything. ADB does appear to be working despite the screen. 

PS C:\Users\hcors\Downloads> adb devices
List of devices attached
5093510030353300        recovery

**Comment by akachyantim** [comment]
I have the exact same experience as @hcors .

**Comment by Ryogo-X** [comment]
@hcors @akachyantim Well... still better than I expected. Can you please try to slide from other sides? It may be that touch orientation is incorrect.
And I'll try to get new test builds later.

**Comment by akachyantim** [comment]
> 
> 
> @hcors @akachyantim Well... still better than I expected. Can you please try to slide from other sides? It may be that touch orientation is incorrect.
> And I'll try to get new test builds later.

Tried the other side and up/down area. no success.
It looks like the screen is frozen. The clock on the screen doesn't change at all.

**Comment by hcors** [comment]
Same here as @akachyantim

**Comment by akachyantim** [comment]
Just checking. ^^
do you have any update? Thank you!

**Comment by Ryogo-X** [comment]
@hcors @akachyantim 
[test_build_v2.zip](https://github.com/Ryogo-Z/nook_ntx_6sl_twrp/files/4322118/test_build_v2.zip)

**Comment by akachyantim** [comment]
This build is better. I see clock is working and 'swipe' animation is working. However, the 'Swipe' doesn't go to the next menu screen. It stuck at the first page.

**Comment by Ryogo-X** [comment]
@akachyantim what exactly do you mean by "the 'Swipe' doesn't go to the next menu screen. It stuck at the first page."?

**Comment by akachyantim** [comment]
video is attached for clarification
[twrp.zip](https://github.com/Ryogo-Z/nook_ntx_6sl_twrp/files/4324561/twrp.zip)

**Comment by Ryogo-X** [comment]
@akachyantim have not seen such behavior before. What if you try to press "Keep read-only"? Also, what TWRP log shows?

**Comment by akachyantim** [comment]
If I "keep read-only" button, it is just blinking once. Nothing happens like "swipe". 
I don't know how to read TWRP log.

**Comment by Ryogo-X** [comment]
@akachyantim @hcors 
[twrp_test_image_2a.zip](https://github.com/Ryogo-Z/nook_ntx_6sl_twrp/files/4327042/twrp_test_image_2a.zip)
[twrp_test_image_2b.zip](https://github.com/Ryogo-Z/nook_ntx_6sl_twrp/files/4327040/twrp_test_image_2b.zip)

**Comment by akachyantim** [comment]
"twrp_test_image_2a.zip" acts exactly same as "test_build_v2.zip" 
"twrp_test_image_2b.zip" acts exactly same as "test_build_v1.zip" -> screen frozen

**Comment by akachyantim** [comment]
Just thinking, if it helps, 
I can loan my device to you for easier debugging. :-)

**Comment by Ryogo-X** [comment]
@akachyantim thanks, but I don't think it would be a good idea to send device to Ukraine and back. Maybe someday I'll buy one myself. 
And now I need to think a bit about what could we do next, since this device already behaves quite different from any other similar device.

**Comment by akachyantim** [comment]
Oh I see. Sure.
Thank you!

**Comment by Ryogo-X** [comment]
@hcors @akachyantim well, good news is - I've bought a reader myself, now just need wait 'till it arrive.

**Comment by Ryogo-X** [comment]
@hcors @akachyantim so, my book finally arrived and here's a little something for you: 
[recovery.zip](https://github.com/Ryogo-Z/nook_ntx_6sl_twrp/files/4395868/recovery.zip)

**Comment by Ryogo-X** [comment]
TWRP for GLP 7.8 added to release page.

**Comment by akachyantim** [comment]
Thank you. It works GREAT!
