### ISSUE TITLE
Does it support mobiscribe 6.8？

### ISSUE THREAD

**Issue by mjkillly** [Ryogo-Z/nook_ntx_6sl_twrp#4]
The mobiscribe 6.8 inches 's recovery is poor，but it's also ntx_6sl，can this recovery work for it？

**Comment by Ryogo-X** [comment]
Hi @mjkillly.

In general - yes, but nobody tried it. It is possible that config changes and a custom recovery build may be required to support MobiScribe 6.8"
There are 4 different build of TWRP available for ntx_6sl platform, you may try to test them if you want:
https://github.com/Ryogo-Z/tolino_ntx_6sl_twrp/releases
https://github.com/Ryogo-Z/nook_ntx_6sl_twrp/releases
https://github.com/Ryogo-Z/tolino_shine3_twrp/releases

I would not recommend to flash any of this, but instead you can boot them without flashing by using
`fastboot boot twrp.img`
Just trying to boot twrp should be safe unless you will try to flash / erase something in booted twrp.
To be sure that doing any operations is safe one would need to check if recovery fstab and firmware fstab are equal.

**Comment by mjkillly** [comment]
Thanks for your reply.
I've capture the update.zip from firmware upgrade of Mobiscribe 6.8",unzip,get "recovery.fstab" and "fstab.E60QR2",looks quite different from Nook and Tolino's files.Is it possible to make this fit for the TWRP recovery?

------------------
recovery.fstab
-------------------
# Android fstab file.
#<src>                                                  <mnt_point>         <type>    <mnt_flags and options>                       <fs_mgr_flags>
# The filesystem that contains the filesystem checker binary (typically /system) cannot
# specify MF_CHECK, and must come before any filesystems that do specify MF_CHECK

/devices/platform/sdhci-esdhc-imx.1/mmc_host/mmc1 /mnt/media_rw/extsd vfat defaults voldmanaged=extsd:auto
#/devices/platform/fsl-ehci /mnt/media_rw/udisk vfat defaults voldmanaged=udisk:auto
/dev/block/mmcblk0p5    /system      ext4    rw                                                                               wait
/dev/block/mmcblk0p7    /data        ext4    nosuid,nodev,nodiratime,noatime,nomblk_io_submit,noauto_da_alloc,errors=panic    wait,encryptable=footer
/dev/block/mmcblk0p6    /cache       ext4    nosuid,nodev,nomblk_io_submit                                                    wait
/dev/block/mmcblk0p8    /device      ext4    ro,nosuid,nodev                                                                  wait
/dev/block/mmcblk0p1    /boot        emmc    defaults                                                                         defaults
/dev/block/mmcblk0p2    /recovery    emmc    defaults                                                                         defaults
/dev/block/mmcblk0p9    /misc        emmc    defaults                                                                         defaults

#mount via init
/dev/block/mmcblk0p4    /mnt/media_rw/sdcard1        vfat    defaults                                                         defaults

#mount via vold
#Android 4.4 Vold does not offer a partition number to mount specific partition
#so that we decide to mount disk and then select partition to mount in Vold source code
#/devices/platform/sdhci-esdhc-imx.3/mmc_host/mmc0 auto vfat defaults voldmanaged=sdcard1:auto,noemulatedsd 
#/devices/platform/sdhci-esdhc-imx.3/mmc_host/mmc0/mmc0:0001/block/mmcblk0/mmcblk0p4  auto        vfat    defaults                                                         voldmanaged=sdcard1:auto

--------------
fstab.E60QR2
--------------
# Android fstab file.
#<src>                                                  <mnt_point>         <type>    <mnt_flags and options>                       <fs_mgr_flags>
# The filesystem that contains the filesystem checker binary (typically /system) cannot
# specify MF_CHECK, and must come before any filesystems that do specify MF_CHECK
/devices/platform/sdhci-esdhc-imx.1/mmc_host/mmc1 /mnt/media_rw/extsd vfat defaults voldmanaged=extsd:auto
#/devices/platform/fsl-ehci /mnt/media_rw/udisk vfat defaults voldmanaged=udisk:auto
/dev/block/mmcblk0p5    /system      ext4    rw                                                                               wait
/dev/block/mmcblk0p7    /data        ext4    nosuid,nodev,nodiratime,noatime,nomblk_io_submit,noauto_da_alloc,errors=panic    wait,encryptable=footer
/dev/block/mmcblk0p6    /cache       ext4    nosuid,nodev,nomblk_io_submit                                                    wait
/dev/block/mmcblk0p8    /device      ext4    ro,nosuid,nodev                                                                  wait
/dev/block/mmcblk0p1    /boot        emmc    defaults                                                                         defaults
/dev/block/mmcblk0p2    /recovery    emmc    defaults                                                                         defaults
/dev/block/mmcblk0p9    /misc        emmc    defaults                                                                         defaults
#mount via init
#/dev/block/mmcblk0p4    /mnt/media_rw/sdcard1        vfat    defaults                                                         defaults
/devices/platform/sdhci-esdhc-imx.3/mmc_host/mmc0 auto vfat defaults voldmanaged=sdcard1:4,noemulatedsd

**Comment by zeeroh** [comment]
@mjkillly Did you end up attempting this with the mobiscribe? I assume you considered it too risky and abandoned the idea. But if not, I am curious to hear how it turned out.
